### ISSUE TITLE
Feature request: auto-strip whitespace on save

### ISSUE THREAD

**Issue by unikitty37** [mads-hartmann/Whitespace.tmbundle#1]
This is a really useful bundle! The only thing that would make it more useful is if it could do the cleanup work for me :)

(Is that even possible within TM2 bundles, or do we need to ask Allan to add support?)

**Comment by mads-hartmann** [comment]
Hi, there is already very useful commands for this :) 

In the Text bundle there is a menu item named Remove Trailing Spaces in Document / Selection which will remove trailing whitespace 

and in the source bundle there is two commands 
- Convert Tabs to Spaces
- Convert Spaces to Tabs

With these commands you should be all set :)

**Comment by unikitty37** [comment]
Thanks — typically, I noticed these commands about ten seconds before you replied. One keyboard shortcut later and it's all good :)

**Comment by mads-hartmann** [comment]
Heh, no problem :)
