### ISSUE TITLE
Don't match WS if we have just typed it.

### ISSUE THREAD

**Issue by schinckel** [mads-hartmann/Whitespace.tmbundle#4]
When typing a line, it's rather jarring to have the red invalid space appear after we type each space. It would be great if it only showed this when we hadn't just typed that character: perhaps it's possible to get the cursor position or something?

(I had a bit of a look around, but could not figure out how to get a scope that says we have the cursor next to us).

**Comment by mads-hartmann** [comment]
I don't think this is possible :/ I'll ask around

**Comment by mads-hartmann** [comment]
I confirmed that this is currently not possible. I'll close the ticket for now and re-open it when it's possible to implement.
