### ISSUE TITLE
Autotrimming trailing whitespace

### ISSUE THREAD

**Issue by wailqill** [mads-hartmann/Whitespace.tmbundle#6]
Great bundle.

Can it be made to automatically trim the trailing whitespace away on save?

**Comment by mads-hartmann** [comment]
There is already a command that removes trailing whitespace in the text bundle called 'Remove Trailing Whitespace in Document' and you can make that run on save by giving it the semantic class 'callback.document.did-save' in the bundle editor :)

**Comment by wailqill** [comment]
Ooops. Thx =)
