### ISSUE TITLE
Showing free lines as mistakes

### ISSUE THREAD

**Issue by cristibaluta** [mads-hartmann/Whitespace.tmbundle#7]
When you hit enter at the end of a line TM will put you at the same indentation. If you leave a line free, whitespace consider that it is wrong and you have to remove the indentations. I consider that this is perfectly fine and is a big waste of time if i do that whitespace thinks.

**Comment by mads-hartmann** [comment]
Yeah - I've been finding this annoying as well :) I'll fix it when I find the time.

**Comment by mads-hartmann** [comment]
Should be fixed by https://github.com/mads379/Whitespace.tmbundle/pull/9
